#!/usr/bin/python3
import sys
import time

from autocorrect import Speller
from autocorrect.typos import Word

english = {
    "access": "acess",
    "accommodation": "accomodation|acommodation|acomodation",
    "arranged": "aranged|arrainged",
    "basically": "basicaly",
    "beginning": "begining",
    "benefit": "benifit",
    "benefits": "benifits",
    "between": "beetween",
    "biscuits": "biscits|biscuts|bisquits|buiscits|buiscuts",
    "built": "biult",
    "career": "carrer",
    "certain": "cirtain",
    "challenges": "chalenges|chalenges",
    "chapter": "chaper|chaphter|chaptur",
    "clerical": "clearical",
    "committee": "comittee",
    "completely": "completly",
    "consider": "concider",
    "considerable": "conciderable",
    "decide": "descide",
    "decided": "descided",
    "definition": "defenition",
    "definitions": "defenitions",
    "description": "discription",
    "different": "diffrent",
    "driven": "dirven",
    "establishing": "astablishing|establising",
    "extended": "extented",
    "extremely": "extreamly",
    "families": "familes",
    "february": "febuary",
    "gallery": "galery|gallary|gallerry|gallrey",
    "hierarchy": "hierchy",
    "inconvenient": "inconvienient|inconvient|inconvinient",
    "initial": "intial",
    "level": "leval",
    "levels": "levals",
    "literature": "litriture",
    "magnificent": "magnificnet|magificent|magnifcent|magnifecent",
    "management": "managment",
    "monitoring": "monitering",
    "necessary": "neccesary|necesary|neccesary|necassary|necassery",
    "parallel": "paralel|paralell|parrallel|parralell|parrallell",
    "particular": "particulaur",
    "perhaps": "perhapse",
    "position": "possition",
    "possible": "possable",
    "pronunciation": "pronounciation",
    "questionnaire": "questionaire",
    "receive": "recieve",
    "scarcely": "scarcly|scarecly|scarely",
    "scissors": "scisors|sissors",
    "singular": "singulaur",
    "someone": "somone",
    "southern": "southen",
    "special": "speaical|specail|specal|speical",
    "triangular": "triangulaur",
    "unexpected": "unexpcted|unexpeted|unexspected",
    "unfortunately": "unfortunatly",
    "unique": "uneque",
    "useful": "usefull",
    "valuable": "valubale|valuble",
    "variable": "varable",
    "variant": "vairiant",
    "various": "vairious",
    "visitors": "vistors",
    "voting": "voteing",
}

sentences = {
    "There is no coming to consciousness without pain.": "There is no comin to consiousnes without pain.",
    "Hey! Mr. Tambourine Man, play a song for me,": "Hey! Mr. Tambourime Man, play a ssong for me,",
    "I'm not sleepy and there is no place I'm going to.": "I'm not sleapy and tehre is no place I'm giong to.",
}

upper = {
    "USA": "USA",
    "camelCased": "camelCased",
    "I": "I",
}

only_replacements = {
    "other": "ather",
    "health": "heaith",
    "should": "shauld",
    "mental": "mentat",
    "also": "aiso",
    "order": "arder",
    "they": "thew",  # they, not the
    "here": "herw",  # here, not her
}

tamil_words_all_correct = {
    "தமிழ்": "தமிழ|தமி|தழ்மி|தமில்|தமிள்", 
    "அன்னம்": "அண்ணம்|அன்ன|அனன்ம்",
    "கலைச்சொல்": "கலைட்சொல்|கலைச்சொல|களைச்சொல்|கழைச்சொல்|கலைசசொல்",
    "அகராதி": "அகராத|அகறாதி|அகரதி|அகரா|அகராதீ",
    "கண்": "கன்",
    "நாற்காலி": "நாட்காலி|நாகாலி|நாற்கால|நாற்கா",
    "தொலைக்காட்சி": "தொலைகாட்சி|தொலைக்காட்ச்சி|தொலைக்காடசி|தொலைக்காசி",
    "உருளைக்கிழங்கு": "உருளைக்கிழக்கு|உருளைகிழங்கு|உருலைக்கிழங்கு|உருழைக்கிழங்கு",
    "எச்சரிக்கை": "எச்சரிகை|எச்சரக்கை|எசரிக்கை",
    "மகிழ்ச்சி": "மகிழ்ட்சி|மகிழ்சி|மகில்ச்சி|மகிள்ச்சி|மகிச்சி",
    "கூச்சம்": "கூட்சம்|கூஞ்சம்|கூசம்",
    "வேட்டையாடுதல்": "வேடையாடுதல்|வேட்டையடுதல்|வெட்டையாடுதல்",
    "நகைச்சுவை": "நகைசுவை|நகைட்சுவை|நகச்சுவை",
    "முக்கோணம்": "முகோணம்|முக்கோனம்|மூக்கோணம்",
    "கடற்கரை": "கடகரை|கடல்கரை|கடற்கறை",
    "மருந்துக்கடை": "மருந்துகடை|மருத்துக்கடை",
    "பயணியர்": "பயனியர்",
    "விழிப்புணர்வு": "விழிபுணர்வு|விழிப்புனர்வு|விளிப்புணர்வு",
    "பல்கலைக்கழகம்": "பல்கலைகழகம்|பல்கலைக்கலகம்|பல்களைக்கழகம்",
    "உலகம்": "உளகம்|உழகம்|உலகாம்|ஊலகம்",
    "புத்திசாலி": "புதிசாலி|புத்திசாளி|புத்திசாழி|புத்திசலி|புத்திச்சாலி",
}

single_typos_me = {
    "ae",
    "ame",
    "be",
    "bme",
    "ce",
    "cme",
    "de",
    "dme",
    "e",
    "ee",
    "em",
    "eme",
    "fe",
    "fme",
    "ge",
    "gme",
    "he",
    "hme",
    "ie",
    "ime",
    "je",
    "jme",
    "ke",
    "kme",
    "le",
    "lme",
    "m",
    "ma",
    "mae",
    "mb",
    "mbe",
    "mc",
    "mce",
    "md",
    "mde",
    "me",
    "mea",
    "meb",
    "mec",
    "med",
    "mee",
    "mef",
    "meg",
    "meh",
    "mei",
    "mej",
    "mek",
    "mel",
    "mem",
    "men",
    "meo",
    "mep",
    "meq",
    "mer",
    "mes",
    "met",
    "meu",
    "mev",
    "mew",
    "mex",
    "mey",
    "mez",
    "mf",
    "mfe",
    "mg",
    "mge",
    "mh",
    "mhe",
    "mi",
    "mie",
    "mj",
    "mje",
    "mk",
    "mke",
    "ml",
    "mle",
    "mm",
    "mme",
    "mn",
    "mne",
    "mo",
    "moe",
    "mp",
    "mpe",
    "mq",
    "mqe",
    "mr",
    "mre",
    "ms",
    "mse",
    "mt",
    "mte",
    "mu",
    "mue",
    "mv",
    "mve",
    "mw",
    "mwe",
    "mx",
    "mxe",
    "my",
    "mye",
    "mz",
    "mze",
    "ne",
    "nme",
    "oe",
    "ome",
    "pe",
    "pme",
    "qe",
    "qme",
    "re",
    "rme",
    "se",
    "sme",
    "te",
    "tme",
    "ue",
    "ume",
    "ve",
    "vme",
    "we",
    "wme",
    "xe",
    "xme",
    "ye",
    "yme",
    "ze",
    "zme",
}

optional_language_tests = {
    "en": {
        "forbidden": "forbiden",
        "decisions": "deciscions|descisions",
        "supposedly": "supposidly",
        "embellishing": "embelishing",
        "technique": "tecnique",
        "permanently": "perminantly",
        "confirmation": "confermation",
        "appointment": "appoitment",
        "progression": "progresion",
        "accompanying": "acompaning",
        "applicable": "aplicable",
        "regained": "regined",
        "guidelines": "guidlines",
        "surrounding": "serounding",
        "titles": "tittles",
        "unavailable": "unavailble",
        "advantageous": "advantageos",
        "brief": "brif",
        "appeal": "apeal",
        "consisting": "consisiting",
        "clerk": "cleark|clerck",
        "component": "componant",
        "favourable": "faverable",
        "separation": "seperation",
        "search": "serch",
        "receive": "recieve",
        "employees": "emploies",
        "prior": "piror",
        "resulting": "reulting",
        "suggestion": "sugestion",
        "opinion": "oppinion",
        "cancellation": "cancelation",
        "criticism": "citisum",
        "useful": "usful",
        "humour": "humor",
        "anomalies": "anomolies",
        "would": "whould",
        "doubt": "doupt",
        "examination": "eximination",
        "therefore": "therefoe",
        "recommend": "recomend",
        "separated": "seperated",
        "successful": "sucssuful|succesful",
        "apparent": "apparant",
        "occurred": "occureed",
        "particular": "paerticulaur",
        "pivoting": "pivting",
        "announcing": "anouncing",
        "challenge": "chalange",
        "arrangements": "araingements",
        "proportions": "proprtions",
        "organized": "oranised",
        "accept": "acept",
        "dependence": "dependance",
        "unequalled": "unequaled",
        "numbers": "numbuers",
        "sense": "sence",
        "conversely": "conversly",
        "provide": "provid",
        "arrangement": "arrangment",
        "responsibilities": "responsiblities",
        "fourth": "forth",
        "ordinary": "ordenary",
        "description": "desription|descvription|desacription",
        "inconceivable": "inconcievable",
        "data": "dsata",
        "register": "rgister",
        "supervision": "supervison",
        "encompassing": "encompasing",
        "negligible": "negligable",
        "allow": "alow",
        "operations": "operatins",
        "executed": "executted",
        "interpretation": "interpritation",
        "hierarchy": "heiarky",
        "indeed": "indead",
        "years": "yesars",
        "through": "throut",
        "committee": "committe",
        "inquiries": "equiries",
        "before": "befor",
        "continued": "contuned",
        "permanent": "perminant",
        "choose": "chose",
        "virtually": "vertually",
        "correspondence": "correspondance",
        "eventually": "eventully",
        "lonely": "lonley",
        "profession": "preffeson",
        "they": "thay",
        "now": "noe",
        "desperately": "despratly",
        "university": "unversity",
        "adjournment": "adjurnment",
        "possibilities": "possablities",
        "stopped": "stoped",
        "mean": "meen",
        "weighted": "wagted",
        "adequately": "adequattly",
        "shown": "hown",
        "matrix": "matriiix",
        "profit": "proffit",
        "encourage": "encorage",
        "collate": "colate",
        "disaggregate": "disaggreagte|disaggreaget",
        "receiving": "recieving|reciving",
        "proviso": "provisoe",
        "umbrella": "umberalla",
        "approached": "aproached",
        "pleasant": "plesent",
        "difficulty": "dificulty",
        "appointments": "apointments",
        "base": "basse",
        "conditioning": "conditining",
        "earliest": "earlyest",
        "beginning": "begining",
        "universally": "universaly",
        "unresolved": "unresloved",
        "length": "lengh",
        "exponentially": "exponentualy",
        "utilized": "utalised",
        "set": "et",
        "surveys": "servays",
        "families": "familys",
        "system": "sysem",
        "approximately": "aproximatly",
        "their": "ther",
        "scheme": "scheem",
        "speaking": "speeking",
        "repetitive": "repetative",
        "inefficient": "ineffiect",
        "geneva": "geniva",
        "exactly": "exsactly",
        "immediate": "imediate",
        "appreciation": "apreciation",
        "luckily": "luckeley",
        "eliminated": "elimiated",
        "believe": "belive",
        "appreciated": "apreciated",
        "readjusted": "reajusted",
        "were": "wer|where",
        "feeling": "fealing",
        "and": "anf",
        "false": "faulse",
        "seen": "seeen",
        "interrogating": "interogationg",
        "academically": "academicly",
        "relatively": "relativly|relitivly",
        "traditionally": "traditionaly",
        "studying": "studing",
        "majority": "majorty",
        "build": "biuld",
        "aggravating": "agravating",
        "transactions": "trasactions",
        "arguing": "aurguing",
        "sheets": "sheertes",
        "successive": "sucsesive|sucessive",
        "segment": "segemnt",
        "especially": "especaily",
        "later": "latter",
        "senior": "sienior",
        "dragged": "draged",
        "atmosphere": "atmospher",
        "drastically": "drasticaly",
        "particularly": "particulary",
        "visitor": "vistor",
        "session": "sesion",
        "continually": "contually",
        "availability": "avaiblity",
        "busy": "buisy",
        "parameters": "perametres",
        "surroundings": "suroundings|seroundings",
        "employed": "emploied",
        "adequate": "adiquate",
        "handle": "handel",
        "means": "meens",
        "familiar": "familer",
        "between": "beeteen",
        "overall": "overal",
        "timing": "timeing",
        "committees": "comittees|commitees",
        "queries": "quies",
        "econometric": "economtric",
        "erroneous": "errounous",
        "decides": "descides",
        "reference": "refereence|refference",
        "intelligence": "inteligence",
        "edition": "ediion|ediition",
        "are": "arte",
        "apologies": "appologies",
        "thermawear": "thermawere|thermawhere",
        "techniques": "tecniques",
        "voluntary": "volantary",
        "subsequent": "subsequant|subsiquent",
        "currently": "curruntly",
        "forecast": "forcast",
        "weapons": "wepons",
        "routine": "rouint",
        "neither": "niether",
        "approach": "aproach",
        "available": "availble",
        "recently": "reciently",
        "ability": "ablity",
        "nature": "natior",
        "commercial": "comersial",
        "agencies": "agences",
        "however": "howeverr",
        "suggested": "sugested",
        "career": "carear",
        "many": "mony",
        "annual": "anual",
        "according": "acording",
        "receives": "recives|recieves",
        "interesting": "intresting",
        "expense": "expence",
        "relevant": "relavent|relevaant",
        "table": "tasble",
        "throughout": "throuout",
        "conference": "conferance",
        "sensible": "sensable",
        "described": "discribed|describd",
        "union": "unioun",
        "interest": "intrest",
        "flexible": "flexable",
        "refered": "reffered",
        "controlled": "controled",
        "sufficient": "suficient",
        "dissension": "desention",
        "adaptable": "adabtable",
        "representative": "representitive",
        "irrelevant": "irrelavent",
        "unnecessarily": "unessasarily",
        "applied": "upplied",
        "apologised": "appologised",
        "these": "thees|thess",
        "choices": "choises",
        "will": "wil",
        "procedure": "proceduer",
        "shortened": "shortend",
        "manually": "manualy",
        "disappointing": "dissapoiting",
        "excessively": "exessively",
        "comments": "coments",
        "containing": "containg",
        "develop": "develope",
        "credit": "creadit",
        "government": "goverment",
        "acquaintances": "aquantences",
        "orientated": "orentated",
        "widely": "widly",
        "advise": "advice",
        "difficult": "dificult",
        "investigated": "investegated",
        "bonus": "bonas",
        "conceived": "concieved",
        "nationally": "nationaly",
        "compared": "comppared|compased",
        "moving": "moveing",
        "necessity": "nessesity",
        "opportunity": "oppertunity|oppotunity|opperttunity",
        "thoughts": "thorts",
        "equalled": "equaled",
        "variety": "variatry",
        "analysis": "analiss|analsis|analisis",
        "patterns": "pattarns",
        "qualities": "quaties",
        "easily": "easyly",
        "organization": "oranisation|oragnisation",
        "the": "thw|hte|thi",
        "corporate": "corparate",
        "composed": "compossed",
        "enormously": "enomosly",
        "financially": "financialy",
        "functionally": "functionaly",
        "discipline": "disiplin",
        "announcement": "anouncement",
        "progresses": "progressess",
        "except": "excxept",
        "recommending": "recomending",
        "mathematically": "mathematicaly",
        "source": "sorce",
        "combine": "comibine",
        "input": "inut",
        "careers": "currers|carrers",
        "resolved": "resoved",
        "demands": "diemands",
        "unequivocally": "unequivocaly",
        "suffering": "suufering",
        "immediately": "imidatly|imediatly",
        "accepted": "acepted",
        "projects": "projeccts",
        "necessary": "necasery|nessasary|nessisary|neccassary",
        "journalism": "journaism",
        "unnecessary": "unessessay",
        "night": "nite",
        "output": "oputput",
        "security": "seurity",
        "essential": "esential",
        "beneficial": "benificial|benficial",
        "explaining": "explaning",
        "supplementary": "suplementary",
        "questionnaire": "questionare",
        "employment": "empolyment",
        "proceeding": "proceding",
        "decision": "descisions|descision",
        "per": "pere",
        "discretion": "discresion",
        "reaching": "reching",
        "analysed": "analised",
        "expansion": "expanion",
        "although": "athough",
        "subtract": "subtrcat",
        "analysing": "aalysing",
        "comparison": "comparrison",
        "months": "monthes",
        "hierarchal": "hierachial",
        "misleading": "missleading",
        "commit": "comit",
        "auguments": "aurgument",
        "within": "withing",
        "obtaining": "optaning",
        "accounts": "acounts",
        "primarily": "pimarily",
        "operator": "opertor",
        "accumulated": "acumulated",
        "extremely": "extreemly",
        "there": "thear",
        "summarys": "sumarys",
        "analyse": "analiss",
        "understandable": "understadable",
        "safeguard": "safegaurd",
        "consist": "consisit",
        "declarations": "declaratrions",
        "minutes": "muinutes|muiuets",
        "associated": "assosiated",
        "accessibility": "accessability",
        "examine": "examin",
        "surveying": "servaying",
        "politics": "polatics",
        "annoying": "anoying",
        "again": "agiin",
        "assessing": "accesing",
        "ideally": "idealy",
        "scrutinized": "scrutiniesed",
        "simular": "similar",
        "personnel": "personel",
        "whereas": "wheras",
        "when": "whn",
        "geographically": "goegraphicaly",
        "gaining": "ganing",
        "requested": "rquested",
        "separate": "seporate",
        "students": "studens",
        "prepared": "prepaired",
        "generated": "generataed",
        "graphically": "graphicaly",
        "suited": "suted",
        "variable": "varible|vaiable",
        "building": "biulding",
        "required": "reequired",
        "necessitates": "nessisitates",
        "together": "togehter",
        "profits": "proffits",
    },
    
    "ta" : {
        "தமிழ்": "தமிழ|தமி|தழ்மி|தமில்|தமிள்", 
        "அன்னம்": "அண்ணம்|அன்ன|அனன்ம்",
        "கலைச்சொல்": "கலைட்சொல்|கலைச்சொல|களைச்சொல்|கழைச்சொல்|கலைசசொல்",
        "அகராதி": "அகராத|அகறாதி|அகரதி|அகரா|அகராதீ",
        "கண்": "கன்",
        "நாற்காலி": "நாட்காலி|நாகாலி|நாற்கால|நாற்கா",
        "தொலைக்காட்சி": "தொலைகாட்சி|தொலைக்காட்ச்சி|தொலைக்காடசி|தொலைக்காசி",
        "உருளைக்கிழங்கு": "உருளைக்கிழக்கு|உருளைகிழங்கு|உருலைக்கிழங்கு|உருழைக்கிழங்கு",
        "எச்சரிக்கை": "எச்சரிகை|எச்சரக்கை|எசரிக்கை",
        "மகிழ்ச்சி": "மகிழ்ட்சி|மகிழ்சி|மகில்ச்சி|மகிள்ச்சி|மகிச்சி",
        "கூச்சம்": "கூட்சம்|கூஞ்சம்|கூசம்",
        "வேட்டையாடுதல்": "வேடையாடுதல்|வேட்டையடுதல்|வெட்டையாடுதல்",
        "நகைச்சுவை": "நகைசுவை|நகைட்சுவை|நகச்சுவை",
        "முக்கோணம்": "முகோணம்|முக்கோனம்|மூக்கோணம்",
        "கடற்கரை": "கடகரை|கடல்கரை|கடற்கறை",
        "மருந்துக்கடை": "மருந்துகடை|மருத்துக்கடை",
        "பயணியர்": "பயனியர்",
        "விழிப்புணர்வு": "விழிபுணர்வு|விழிப்புனர்வு|விளிப்புணர்வு",
        "பல்கலைக்கழகம்": "பல்கலைகழகம்|பல்கலைக்கலகம்|பல்களைக்கழகம்",
        "உலகம்": "உளகம்|உழகம்|உலகாம்|ஊலகம்",
        "புத்திசாலி": "புதிசாலி|புத்திசாளி|புத்திசாழி|புத்திசலி|புத்திச்சாலி",
    },
}


def spelltest(speller, tests, verbose=2):
    n, bad = 0, 0
    for target, incorrect_spellings in tests.items():
        for incorrect_spelling in incorrect_spellings.split("|"):
            n += 1
            w = speller(incorrect_spelling)
            if w != target:
                bad += 1
                if verbose >= 2:
                    print(f"spell({incorrect_spelling}) => {w}; should be {target}")
    if verbose >= 1:
        print(f"bad: {bad}/{n}")
    return bad


def benchmark(name, speller, tests, repetitions=20):
    current_min = float("inf")
    for _ in range(repetitions):
        start = time.time()
        spelltest(speller, tests, verbose=0)
        duration = time.time() - start
        current_min = min(duration, current_min)
    print(f"{name:<24} {current_min:.3f}s    ", end="")
    spelltest(speller, tests, verbose=1)


spell = Speller("en")


def test_english_words():
    assert spelltest(spell, english) == 0


def test_sentences():
    assert spelltest(spell, sentences) == 0


def test_uppercase():
    assert spelltest(spell, upper) == 0


def test_replacements():
    spell_replace = Speller(only_replacements=True)
    assert spelltest(spell_replace, only_replacements) == 0


def test_empty():
    spell.autocorrect_word("")


def test_single_typos():
    word = Word("me", "en")
    assert set(word.typos()) == single_typos_me


def test_tamil():
    spell_ta = Speller("ta")
    assert spelltest(spell_ta, tamil_words_all_correct) == 0


if __name__ == "__main__":
    command = sys.argv[1]

    if command == "quality":
        # this doesn't have to pass 100%, they check the accuracy of correction
        print("\nquality:")
        for lang, test in optional_language_tests.items():
            print(lang + "  ", end="")
            spell = Speller(lang)
            spelltest(spell, test, verbose=1)
    elif command == "benchmark":
        print("\nbenchmarks:")
        spell = Speller("en")
        benchmark("english sentences", spell, sentences)
        spell = Speller("en", fast=True)
        benchmark("english sentences fast", spell, sentences)
        spell = Speller("ta")
        benchmark("tamil words", spell, optional_language_tests["ta"])
       
    elif command == "find_threshold":
        lang = sys.argv[2]
        test = optional_language_tests[lang]
        for i in range(6, 30):
            threshold = int(1.2**i) - 2
            spell = Speller(lang, threshold=threshold)
            bad = spelltest(spell, test, verbose=0)
            print(f"threshold: {threshold:3},   bad: {bad:3}")
    else:
        print("bad option, use:")
        print("./test_all.py [quality | benchmark | find_threshold [lang]]")